name: CI
on:
  push:
    branches: [master, develop, feature/*]
  pull_request:
env:
  CARGO_INCREMENTAL: 0
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: '-D warnings'
  RUSTUP_MAX_RETRIES: 10
jobs:
  node:
    name: Node
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm test
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1
      - name: Compile
        run: cargo test --no-run
      - name: Test
        run: cargo test -- --nocapture --quiet
